import "./globals.css";
import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import classnames from "classnames";
import { TbUpload } from "react-icons/tb";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={classnames(
            inter.className,
            "min-h-screen bg-gradient-to-b from-purple-900 via-blue-950 to-emerald-800 bg-no-repeat"
          )}
        >
          <header className="flex items-center justify-between px-5 py-3">
            <div className="flex items-center gap-5">
              <Link
                className="text-xl font-extrabold transition-transform hover:scale-105"
                href="/"
              >
                OrgMe
              </Link>
              <Link
                href="/upload"
                className="flex items-center space-x-2 rounded-md bg-emerald-600 px-3 py-2 text-sm font-semibold text-white transition-colors hover:bg-emerald-500 focus:outline-none focus:ring-2 focus:ring-emerald-600 focus:ring-offset-2"
              >
                <TbUpload />
                <span>Upload</span>
              </Link>
            </div>

            {/* Account button */}
            <SignedIn>
              <UserButton />
            </SignedIn>
            <SignedOut>
              <SignInButton />
            </SignedOut>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
